development: &development
  domain: 'lvh.me'
  access_key: AKIAJLC5ZMN534TGEHOA
  secret: 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
  ses_host: email.eu-west-1.amazonaws.com

test:
  domain: 'lvh.me'
  access_key: AKIAJLC5ZMN534TGEHOA
  secret: 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
  ses_host: email.eu-west-1.amazonaws.com

staging:
  domain: '52.16.18.38'
  access_key: AKIAJLC5ZMN534TGEHOA
  secret: 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
  ses_host: email.eu-west-1.amazonaws.com

production:
  domain: 'saverd.com'
  access_key: AKIAJLC5ZMN534TGEHOA
  secret: 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
  ses_host: email.eu-west-1.amazonaws.com


